import { FC } from "react";
import AstralObject from "../AstralObject";
import { MegaverseMap, MegaverseRow, MapContainer } from "./styles";

const Megaverse: FC = () => {
  return (
    <MapContainer>
      <MegaverseMap>
        <MegaverseRow>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
        </MegaverseRow>
        <MegaverseRow>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
        </MegaverseRow>
        <MegaverseRow>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
        </MegaverseRow>
        <MegaverseRow>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
        </MegaverseRow>
        <MegaverseRow>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
        </MegaverseRow>
        <MegaverseRow>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
        </MegaverseRow>
        <MegaverseRow>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
        </MegaverseRow>
        <MegaverseRow>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
        </MegaverseRow>
        <MegaverseRow>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
        </MegaverseRow>
        <MegaverseRow>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
        </MegaverseRow>
        <MegaverseRow>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
         <AstralObject/>
        </MegaverseRow>
      </MegaverseMap>
    </MapContainer>
  );
};

export default Megaverse;
